apiVersion: v1
kind: ConfigMap
metadata:
  name: merhaba-service
data:
  merhaba_MESSAGE: "Merhaba from config map!"
  merhaba_NUMBER: "1234"

---
apiVersion: v1
kind: Service
metadata:
  name: merhaba-service-service
spec:
  selector:
    app: merhaba-service
  ports:
  - name: merhaba-service-service-port
    protocol: TCP
    port: 3456
    targetPort: 5432
    nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merhaba-service-deployment
  labels:
    app: merhaba-service
    version: v1
  annotations:
    prometheus.io/port: '9216'
    prometheus.io/scrape: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merhaba-service
  template:
    metadata:
      labels:
        app: merhaba-service
    spec:
      containers:
      - name: merhaba-service
        image: merhaba-service:0.0.5
        envFrom:
        - configMapRef:
            name: merhaba-service
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 200Mi
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /live
            port: 5432
        readinessProbe:
          httpGet:
            path: /ready
            port: 5432
        lifecycle:
          postStart:
            httpGet:
              path: /postStart
              port: 5432          
          preStop:
            httpGet:
              path: /preStop
              port: 5432          
